# Version: 2.0

steps:

  # Setup
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  volumes:
  - name: 'volume'
    path: '/persistent'
  args:
  - '-c'
  - '-e'
  - |
        _TAG=${TAG_NAME}
        _PATH=$(find "./Packages" -name "UGF.*" -type d)

        echo "Setup package at path '$$_PATH'"

        _NAME=$(node -p "require('$$_PATH/package.json').name")
        _VERSION=$(node -p "require('$$_PATH/package.json').version")
        
        if [[ $$_VERSION != $$_TAG ]]; then
         echo "ERROR package version must match tag name ('$$_VERSION' != '$$_TAG')"
         exit 1
        fi

        echo $$_PATH > /persistent/path
        echo $$_NAME > /persistent/name
        echo $$_VERSION > /persistent/version

        echo "Package path '$$_PATH'"
        echo "Package name '$$_NAME'"
        echo "Package version '$$_VERSION'"
  
  # Pack
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  volumes:
  - name: 'volume'
    path: '/persistent'
  args: 
  - '-c'
  - '-e'
  - |
        _PATH=$(cat /persistent/path)

        echo "Pack package '$$_PATH'"
        
        npm pack $$_PATH
  
  # Upload
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  volumes:
  - name: 'volume'
    path: '/persistent'
  secretEnv: ['_USER']
  args:
  - '-c'
  - '-e'
  - |
        _NAME=$(cat /persistent/name)
        _VERSION=$(cat /persistent/version)
        _DEV=https://api.bintray.com/content/unity-game-framework/dev/$$_NAME/$$_VERSION/$$_NAME/-/
        _STABLE=https://api.bintray.com/content/unity-game-framework/stable/$$_NAME/$$_VERSION/$$_NAME/-/

        echo $(curl -T $$_NAME-$$_VERSION.tgz -$$_USER $$_DEV)

        if [[ $$_VERSION != *"-preview"* ]]; then
          echo $(curl -T $$_NAME-$$_VERSION.tgz -$$_USER $$_STABLE)
        fi

  # Publish
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  volumes:
  - name: 'volume'
    path: '/persistent'
  secretEnv: ['_USER']
  args:
  - '-c'
  - '-e'
  - |
        _NAME=$(cat /persistent/name)
        _VERSION=$(cat /persistent/version)
        _DEV=https://api.bintray.com/content/unity-game-framework/dev/$$_NAME/$$_VERSION/publish
        _STABLE=https://api.bintray.com/content/unity-game-framework/stable/$$_NAME/$$_VERSION/publish

        echo $(curl -X POST -$$_USER $$_DEV)

        if [[ $$_VERSION != *"-preview"* ]]; then
          echo $(curl -X POST -$$_USER $$_STABLE)
        fi

# Secrets setup
secrets:
- kmsKeyName: projects/unity-game-framework/locations/global/keyRings/default/cryptoKeys/packages-remote-user
  secretEnv:
    _USER: CiQAFgirOBfQ1m7tfWWHqD6yTDYHNGCGzLLOzJYg3xcfExaFYecSWgAN9TMrOmRTBBE9jo4B1vWyZr0EjqRwPIGDGd9t9Ozo0WZIMJ2IfZbrNuNUPllHeYdwcn0XpeG+11mthqc7GVdmZtsQn8bOw7xHHui38dN5nAQ/hFN3Ie1vEw==